services:
  php:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - postgres_db
    # Instalando o driver do PostgreSQL
    build:
      context: .
      dockerfile: Dockerfile

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: guiwb
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: aula
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
